name: pod-api

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pod_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  postgres_data: